### PR TITLE
Create explicit `hyperdrive-net` network and provide configurable mapping to network name and external 

### PR DESCRIPTION
**Pull request by jshiv**
This PR addresses the issue of running a hyperdrive client on the same machine as a rocketpool node and allows the containers to network through the `rocketpool_net` docker network

Adding the explicit network name `hyperdrive-net` and making the name and external fields configurable
```
networks:
  hyperdrive-net:
    name: {{.Hyperdrive.DockerNetwork}}
    external: {{.Hyperdrive.DockerNetworkIsExternal}}
```

With the the network set to `rocketpool_net` and `external=true`
image

The clients can be connected to like so
image
image

image

Testing
* Tested with rp rpc ports set to closed and to external hosts
* Tested with rp old cli and beta v2
* Tested with hyperdrive running full node to ensure it works as a standalone

The new docker compose looks like:
```
hyperdrive s compose

name: hyperdrive
services:
  daemon:
    cap_add:
      - dac_override
      - chown
    cap_drop:
      - all
    command:
      - --user-dir
      - /home/pi/.hyperdrive
      - -m
      - stakewise
    container_name: hyperdrive_daemon
    image: nodeset/hyperdrive:v0.4.2-b1
    networks:
      hyperdrive-net: null
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
      - type: bind
        source: /home/pi/.hyperdrive
        target: /home/pi/.hyperdrive
        bind:
          create_host_path: true
      - type: bind
        source: /home/pi/.hyperdrive/data
        target: /home/pi/.hyperdrive/data
        bind:
          create_host_path: true
      - type: bind
        source: /usr/share/hyperdrive/scripts
        target: /usr/share/hyperdrive/scripts
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /var/lib/hyperdrive/global
        target: /var/lib/hyperdrive/global
        bind:
          create_host_path: true
      - type: bind
        source: /var/lib/hyperdrive/data/hyperdrive
        target: /var/lib/hyperdrive/data/hyperdrive
        bind:
          create_host_path: true
    x-rp-comment: Add your customizations below this line
  sw_daemon:
    cap_add:
      - dac_override
      - chown
    cap_drop:
      - all
    command:
      - --module-dir
      - /home/pi/.hyperdrive/data/modules/stakewise
    container_name: hyperdrive_sw_daemon
    image: nodeset/hyperdrive-stakewise:v0.1.1
    networks:
      hyperdrive-net: null
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    user: root
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
      - type: bind
        source: /home/pi/.hyperdrive
        target: /home/pi/.hyperdrive
        bind:
          create_host_path: true
      - type: bind
        source: /home/pi/.hyperdrive/data/modules/stakewise
        target: /home/pi/.hyperdrive/data/modules/stakewise
        bind:
          create_host_path: true
    x-rp-comment: Add your customizations below this line
  sw_operator:
    cap_add:
      - dac_override
    cap_drop:
      - all
    command:
      - src/main.py
      - start
      - --data-dir=/home/pi/.hyperdrive/data/modules/stakewise
      - --deposit-data-file=/home/pi/.hyperdrive/data/modules/stakewise/deposit-data.json
      - --network=holesky
      - --vault=0x646F5285D195e08E309cF9A5aDFDF68D6Fcc51C4
      - --execution-endpoints=http://rocketpool_eth1:8545
      - --consensus-endpoints=http://rocketpool_eth2:5052
      - --hot-wallet-file=/home/pi/.hyperdrive/data/modules/stakewise/wallet.json
      - --hot-wallet-password-file=/home/pi/.hyperdrive/data/modules/stakewise/password.txt
      - --keystores-dir=/home/pi/.hyperdrive/data/modules/stakewise/validators/stakewise
      - --keystores-password-file=/home/pi/.hyperdrive/data/modules/stakewise/validators/stakewise/secret.txt
      - --enable-metrics
      - --metrics-host=0.0.0.0
      - --max-fee-per-gas-gwei=100
    container_name: hyperdrive_sw_operator
    image: europe-west4-docker.pkg.dev/stakewiselabs/public/v3-operator:v1.2.2
    networks:
      hyperdrive-net: null
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    user: root
    volumes:
      - type: bind
        source: /home/pi/.hyperdrive/data/modules/stakewise
        target: /home/pi/.hyperdrive/data/modules/stakewise
        bind:
          create_host_path: true
    x-rp-comment: Add your customizations below this line
  sw_vc:
    cap_add:
      - dac_override
    cap_drop:
      - all
    command:
      - /usr/share/hyperdrive/scripts/start-vc.sh
    container_name: hyperdrive_sw_vc
    entrypoint:
      - sh
    environment:
      BITFLY_NODE_METRICS_ENDPOINT: https://beaconcha.in/api/v1/client/metrics
      BITFLY_NODE_METRICS_MACHINE_NAME: Hyperdrive Node
      BITFLY_NODE_METRICS_SECRET: ""
      BN_API_ENDPOINT: http://rocketpool_eth2:5052
      BN_RPC_ENDPOINT: ""
      CLIENT: lighthouse
      DOPPELGANGER_DETECTION: "true"
      ENABLE_BITFLY_NODE_METRICS: "false"
      ENABLE_METRICS: "false"
      FALLBACK_BN_API_ENDPOINT: ""
      FALLBACK_BN_RPC_ENDPOINT: ""
      FEE_RECIPIENT: 0xc98F25BcAA6B812a07460f18da77AF8385be7b56
      GRAFFITI: HD v0.4.2-b1
      NETWORK: holesky
      VC_ADDITIONAL_FLAGS: ""
      VC_METRICS_PORT: "9101"
    image: sigp/lighthouse:v5.1.3-modern
    networks:
      hyperdrive-net: null
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    stop_grace_period: 3m0s
    user: root
    volumes:
      - type: bind
        source: /usr/share/hyperdrive/scripts
        target: /usr/share/hyperdrive/scripts
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/pi/.hyperdrive/data/modules/stakewise/validators
        target: /validators
        bind:
          create_host_path: true
    x-rp-comment: Add your customizations below this line
networks:
  hyperdrive-net:
    name: rocketpool_net
    external: true
```

### CODE REVIEW

**Comment by jshiv** [comment]
@jclapis Hoping this helps

**Review by Ahmarfi — CHANGES_REQUESTED** [review]
📀

**Comment by jclapis** [comment]
> @jclapis Hoping this helps

This is definitely on the right track, thank you for getting the ball rolling on this. I think it'll probably be better received if we keep a canonical `hyperdrive_net` (or more accurately `<ProjectName>_net`) for the sake of ownership, but add a setting called "Additional Docker Networks" separated by a comma or semi-colon or something. All of those would be added as supplemental (externally-managed) networks in the templates. That will let people access the RP Docker network in HD containers, as well as other Docker networks they run too.

Something like this in each template:
```
services:
  <...>:
    networks:
      - net
      {{- range $network := .Hyperdrive.AdditionalDockerNetworks}}
      - {{$network}}
      {{- end}}

...

networks:
  net:
  {{- range $network := .Hyperdrive.AdditionalDockerNetworks}}
  {{$network}}:
    external: true
  {{- end}}
  ```

Let me know what you think about that. If you're amenable to it but you're busy, I can just put those in since you have maintainer edits enabled.

**Comment by jshiv** [comment]
Hey @jclapis, this is a great idea! Feel free to add it, I won't be able to get around to it until this evening or tomorrow.

**Review by huy-nodeset — APPROVED** [review]

**Comment by VVander** [comment]
Hi @jshiv, hope all is well with you! First of all, I wanted to say thank you again for your contributions to Hyperdrive. NodeSet and this project are only as strong as the community behind it!

I'm reaching out today because we are working to relicense the Hyperdrive repository to use the MIT license, which will allow others to use and modify Hyperdrive without any requirement to publicly sharing their changes. Notably, this is important for operators who operate as a business instead of as an individual, since the current license already allows individuals to modify for private personal use without sharing. Non-individuals like this may have security concerns with publicizing changes, so we want to relicense HD to allow for this use case.

To allow for this, we're asking all prior contributors to agree to a contributor license agreement (CLA) which makes it clear that your past contributions are assigned to our team so that we can relicense this repository. I'm going to paste the agreement below, and all we need from you is a comment saying "I agree" or something similar.

Thanks in advance!

-----------

I hereby grant to NodeSet, LLC (“Project”) the following rights regarding my contributions to the project currently hosted at https://github.com/nodeset-org/hyperdrive (the “Project”):

**Definitions**

“Contribution” means any original work of authorship, including any modifications or additions to existing code, documentation, tests, or other materials, that I submit to the Project, whether submitted via pull request, patch, issue, or other means.
“Project Copyright” means all copyrights and related rights in Contributions.

**Grant of Copyright License**
I hereby grant to the Project and its successors, assigns, and licensees a perpetual, worldwide, non-exclusive, irrevocable, royalty-free, transferable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute my Contributions, and to incorporate my Contributions into software or other works licensed under any license, including permissive licenses (e.g., MIT), copyleft licenses (e.g., AGPL), or proprietary terms. This license includes the right to grant sublicenses and to relicense the Contributions under different terms.

**Moral Rights**
To the extent permitted by applicable law, I hereby waive (or agree not to assert) any moral rights or similar rights I may have in my Contributions. If waiver is not permitted, I grant the Project the irrevocable right to exercise such rights.

**Representations and Warranties**
I represent and warrant that:

I am the sole author of my Contributions or have the necessary rights from all co‑authors to grant this license.
My Contributions are my original work and do not, to my knowledge, violate any third‑party rights (including copyright, trade secret, trademark, or contractual rights).
I have not assigned, exclusive‑licensed, or otherwise encumbered rights in my Contributions that would conflict with this Agreement.

**No Compensation**
I agree that I will not receive monetary compensation for my Contributions and that the Project may use my Contributions under the terms set forth herein.

**Governing Law**
This Agreement is governed by the laws of Delaware, USA, without regard to conflict of law rules.

**Execution**
By submitting a Contribution to the Project, or by posting a comment of agreement below, I accept and agree to the terms of this Agreement.

-----------

Please just post a comment below saying "I agree" or something similar so we have a record of this! Thanks :)

**Comment by jshiv** [comment]
I agree

**Pull request merged**
